services:
  frontend:
    container_name: shoezstore-frontend
    build:
      context: ./
      dockerfile: /prod.Dockerfile
    restart: unless-stopped
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_RAZORPAY_ID: ${NEXT_PUBLIC_RAZORPAY_ID}
    ports:
      - 3000:3000
